name = "weather-data"
compatibility_date = "2024-01-01"

[build]
command = """
apt-get update && \
apt-get install -y maven && \
chmod +x mvnw && \
./mvnw clean package -DskipTests
"""
output = "target"

[build.environment]
JAVA_HOME = "/usr/lib/jvm/java-17-openjdk-amd64"